name: Full Flexis Pipeline

on:
  workflow_dispatch:
  push:

jobs:
  compile-flexis:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: sudo apt update && sudo apt install -y cmake ninja-build g++ clang
      - name: Set up VCPKG
        run: |
          git clone https://github.com/microsoft/vcpkg.git
          ./vcpkg/bootstrap-vcpkg.sh
        env:
          VCPKG_ROOT: ${{ github.workspace }}/vcpkg
      - name: Configure with CMake (Release Preset)
        run: cmake --preset release 
        env:
          VCPKG_ROOT: ${{ github.workspace }}/vcpkg
      - name: Build Flexis (Release Preset)
        run: cmake --build --preset release 
      - name: Upload flexis binary
        uses: actions/upload-artifact@v4
        with:
          name: flexis-binary
          path: ./build/release/bin/flexis

  download-datasets:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: sudo apt update && sudo apt install -y cmake ninja-build g++ clang
      - name: Set up VCPKG
        run: |
          git clone https://github.com/microsoft/vcpkg.git
          ./vcpkg/bootstrap-vcpkg.sh
        env:
          VCPKG_ROOT: ${{ github.workspace }}/vcpkg
      - name: Download and process the datasets 
        run: bash ./scripts/processDatasets.sh --grami
        env:
          VCPKG_ROOT: ${{ github.workspace }}/vcpkg
      - name: Upload processed datasets
        uses: actions/upload-artifact@v4
        with:
          name: processed-datasets
          path: ./data/processed/*.vf3.bin

  run-flexis:
    runs-on: ubuntu-latest
    needs: [compile-flexis, download-datasets]
    steps:
      - uses: actions/checkout@v4
      - name: Download flexis binary
        uses: actions/download-artifact@v4
        with:
          name: flexis-binary
          path: ./bin
      - name: Download datasets
        uses: actions/download-artifact@v4
        with:
          name: processed-datasets
          path: ./datasets
      - name: Make binary executable
        run: chmod +x ./bin/flexis
      - name: Run flexis on mico datasets
        run: ./bin/flexis --input ./datasets/mico.vf3.bin --support 8000 --slider 0.9
      - name: Run flexis on gnutella datasets
        run: ./bin/flexis --input ./datasets/p2p-Gnutella08.vf3.bin --support 8000 --slider 0.9

